# Generated by Django 3.1.7 on 2021-04-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_plots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plots',
            options={'verbose_name_plural': 'Plots'},
        ),
        migrations.RemoveField(
            model_name='plots',
            name='booked_by',
        ),
    ]
