# Generated by Django 3.1.7 on 2021-04-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('parking', '0003_auto_20210405_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedPlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.registration')),
                ('plot_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.plots')),
            ],
            options={
                'verbose_name_plural': 'Booked Plots',
            },
        ),
    ]
