# Generated by Django 3.1.7 on 2021-04-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_bookedplots'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='plot_type',
            field=models.CharField(choices=[('two', 'Two Wheeler'), ('three', 'Three Wheeler'), ('four', 'Four Wheeler')], default='four', max_length=10),
        ),
    ]
