# Generated by Django 3.1.7 on 2021-04-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='fare',
            name='currency',
            field=models.CharField(choices=[('USD', 'DOLLAR'), ('BDT', 'TAKA'), ('CNY', 'YUAN')], default='CNY', max_length=3),
        ),
    ]
