# Generated by Django 3.1.7 on 2021-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_fare_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedplots',
            name='plot_id',
            field=models.IntegerField(default=0),
        ),
    ]
