# Generated by Django 3.1.7 on 2021-04-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_bookedplots_is_exited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicleentry',
        ),
        migrations.DeleteModel(
            name='Vehicleexit',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='contactno',
            new_name='contact_no',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='space',
        ),
        migrations.AddField(
            model_name='complaints',
            name='complaint_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
