# Generated by Django 3.1.7 on 2021-04-01 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=200)),
                ('contact_number', models.CharField(default='', max_length=11)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10)),
                ('question', models.CharField(choices=[('book', 'What Is your favorite book?'), ('food', 'What is your favorite food?'), ('city', 'What city were you born in?'), ('place', 'Where is your favorite place to vacation?')], default='book', max_length=10)),
                ('answer', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
