# Generated by Django 3.1.7 on 2021-04-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210405_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='dob',
        ),
    ]
