# Generated by Django 3.1.7 on 2021-04-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_registration_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='question',
        ),
    ]
